# INSTALL DEPENDENCIES

In [ ]:
INITAL_SETUP = False

if INITAL_SETUP:
    %pip install fastkaggle
    %pip install kaggle
    %pip install dotenv
    %pip install ipdb

In [ ]:
import fastkaggle
import pandas as pd
import numpy as np
from pathlib import Path
import shutil
import os
from fastai.tabular import *
from fastai.tabular.all import *
from fastai.vision.all import *

PATH_LOCAL_PATH_DATA_STORAGE = Path(r'D:\kaggle_data')
COMPETITION_NAME = '104-flowers-garden-of-eden'

# CHECK IF RUNNING ON KAGGLE OR ELSEWHERE

In [ ]:
'Kaggle' if fastkaggle.iskaggle else 'Not Kaggle'

# PREPARE KAGGLE DATA

In [ ]:
# if fastkaggle.iskaggle:
#     path = os.path.join(Path('../input'), COMPETITION_NAME) # generates path containing competition name
    
# else:
#     path_temp = Path(COMPETITION_NAME)
    
#     # check if data is missing from the desired location
#     path_local_competition_data = os.path.join(Path(PATH_LOCAL_PATH_DATA_STORAGE), COMPETITION_NAME) # generates path containing competition name
#     if not os.path.isdir(path_local_competition_data):
#         fastkaggle.setup_comp(COMPETITION_NAME) # download data to temp location
#         dest = shutil.move(path_temp, PATH_LOCAL_PATH_DATA_STORAGE) # move the data to the correct location
    
#     path = path_local_competition_data # update path to point to folder containing data

# print("Data located at: {}".format(str(path)))
    
path = os.path.join(Path(PATH_LOCAL_PATH_DATA_STORAGE), COMPETITION_NAME) # generates path containing competition name

FORMAT_SIZE = "jpeg-192x192"
path = os.path.join(path, 'versions', '1', FORMAT_SIZE) # generates path containing competition name

path

In [ ]:
# import kagglehub

# # Download latest version
# path = kagglehub.dataset_download("msheriey/104-flowers-garden-of-eden")

# print("Path to dataset files:", path)

# Check out the images

In [ ]:
# dls = ImageDataLoaders.from_name_func(
#     path,                                # path to images 
#     get_image_files(path),               # get the list of path for all images
#     valid_pct = 0.25,                    # percentages to use for validation
#     seed = 42,                           # random seed
#     label_func = parent_label,          # labelling for the images
#     item_tfms = Resize(224))             # transform the images to 224x224


dls = ImageDataLoaders.from_folder(
    path,                                # path to images 
    train='train',
    valid='val',
    blocks = (ImageBlock, CategoryBlock),       # specify the type of data
    seed = 42,                           # random seed
    #label_func = parent_label,          # labelling for the images
    get_y = parent_label,
    item_tfms = Resize(224))             # transform the images to 224x224

dls.show_batch()

In [ ]:
for vocab in dls.vocab:
    print(vocab)

# Prepare dataset

TBD if any work needs to be done here. Currently just a placeholder

# Vision Learner

In [ ]:
learn = vision_learner(dls, 
                       resnet18,
                       metrics=[accuracy, error_rate])

In [ ]:
# import torchvision
# torchvision.__version__
# torch.__version__
# import pytorch
# pytorch.__version__

In [ ]:
# import torch
# print(torch.cuda.is_available())
# print(torch.cuda.get_device_name(0))

# Fine Tune
We fine tune this model because we want to take advantage of the pretrained model. This will sever the head and retrain the last layer for our specific application.

In [ ]:
learn.fine_tune(1)

# Quick check of the results

In [ ]:
learn.show_results()

# Prepare testing data

Load testing data....

In [ ]:
test_files = get_image_files(os.path.join(path,'test'))
print("Found {} test files.".format(len(test_files)))

In [ ]:
dls_test = learn.dls.test_dl(test_files)

# Inference

In [ ]:
preds, _, decoded = learn.get_preds(dl=dls_test, with_decoded=True)

Let's check the results

In [ ]:
preds, decoded
predicted_classes = [learn.dls.vocab[i] for i in preds.argmax(dim=1)]
len(predicted_classes)
print('Length of preds:', len(preds))
print('Length of decoded:', len(decoded))
print('Length of predicted_classes:', len(predicted_classes))

In [ ]:
predicted_classes[:10]

In [ ]:
#learn.show_results(dl=dls_test, max_n=5)
#interp = Interpretation.from_learner(learn, dl=dls_test)
#interp.plot_top_losses(9)
#learn.dls.show_results(dls_test.one_batch(), preds, max_n=9)

In [ ]:
predicted_classes[0]

In [94]:
#path_submission = os.path.join(path, 'versions', '1', FORMAT_SIZE) # generates path containing competition name
path_submission = os.path.join(path, '..', 'sample_submission.csv')

submission_csv = pd.read_csv(path_submission, header=0)
submission_csv.head(10)
#submission_csv.iloc[0]

          id  label
0  b48c962e0      0
1  a13d3dfa4      0
2  94269c190      0
3  bcb18c6e4      0
4  d15a4d94c      0
5  914b0e71b      0
6  065c9b5be      0
7  dd8b1aaca      0
8  8c39d1b41      0
9  e2fdce920      0

# Adding predictions to the submission CSV

In [ ]:
dls_test.items

In [86]:
# Get the original filenames/paths
file_names = [f.name.replace('.jpeg', '') for f in dls_test.items]
file_names[:10]

['001e13533',
 '0021f0d33',
 '003882deb',
 '0039e54f0',
 '003b89961',
 '00450d304',
 '0045ce94c',
 '004b88e09',
 '0053fa6c4',
 '006afe0ef']

In [ ]:
# Combine them into a dictionary or list for easy viewing
results = list(zip(file_names, predicted_classes))
results[:10]
d_results = dict(results)
#d_results

In [101]:
print(submission_csv.loc[0, 'id'] )
print(submission_csv.loc[0, 'label'] )

b48c962e0
0

In [ ]:
submission_csv['label'] = submission_csv['label'].astype(str)

for index, row in submission_csv.iterrows():
    #print('index', index)
    #print('row id', row['id'])
    #print('row label', row['label'])
    matched_index = d_results.get(row['id'])
    #print('new label', matched_index)
    submission_csv.loc[index, 'label'] = matched_index
    #print('row label after', row['label'])
    # if index>10:
    #     break'

index 0
new label corn poppy
index 1
new label petunia
index 2
new label rose
index 3
new label wild geranium
index 4
new label common dandelion
index 5
new label sweet william
index 6
new label pink-yellow dahlia
index 7
new label watercress
index 8
new label cosmos
index 9
new label wild geranium
index 10
new label wild rose
index 11
new label wild pansy
index 12
new label yellow iris
index 13
new label colt's foot
index 14
new label toad lily
index 15
new label mexican petunia
index 16
new label common tulip
index 17
new label bougainvillea
index 18
new label iris
index 19
new label rose
index 20
new label anthurium
index 21
new label mallow
index 22
new label grape hyacinth
index 23
new label purple coneflower
index 24
new label daffodil
index 25
new label black-eyed susan
index 26
new label iris
index 27
new label wild rose
index 28
new label lenten rose
index 29
new label iris
index 30
new label buttercup
index 31
new label azalea
index 32
new label wild geranium
index 33
new label bee balm
index 34
new label globe thistle
index 35
new label pink primrose
index 36
new label mallow
index 37
new label marigold
index 38
new label sunflower
index 39
new label daisy
index 40
new label daisy
index 41
new label snapdragon
index 42
new label pink primrose
index 43
new label mexican petunia
index 44
new label rose
index 45
new label wallflower
index 46
new label camellia
index 47
new label wild geranium
index 48
new label peruvian lily
index 49
new label common tulip
index 50
new label wild rose
index 51
new label wild rose
index 52
new label bee balm
index 53
new label buttercup
index 54
new label clematis
index 55
new label artichoke
index 56
new label hippeastrum
index 57
new label corn poppy
index 58
new label iris
index 59
new label wild pansy
index 60
new label windflower
index 61
new label iris
index 62
new label wild pansy
index 63
new label grape hyacinth
index 64
new label snapdragon
index 65
new label thorn apple
index 66
new label lotus
index 67
new label thorn apple
index 68
new label common dandelion
index 69
new label wild rose
index 70
new label windflower
index 71
new label tiger lily
index 72
new label king protea
index 73
new label pincushion flower
index 74
new label marigold
index 75
new label watercress
index 76
new label wild rose
index 77
new label bougainvillea
index 78
new label sunflower
index 79
new label wild geranium
index 80
new label hibiscus
index 81
new label wild geranium
index 82
new label common tulip
index 83
new label windflower
index 84
new label lotus
index 85
new label windflower
index 86
new label wild geranium
index 87
new label wild rose
index 88
new label wild rose
index 89
new label magnolia
index 90
new label azalea
index 91
new label morning glory
index 92
new label iris
index 93
new label windflower
index 94
new label wild geranium
index 95
new label lotus
index 96
new label wallflower
index 97
new label daisy
index 98
new label azalea
index 99
new label anthurium
index 100
new label californian poppy
index 101
new label iris
index 102
new label wild rose
index 103
new label petunia
index 104
new label camellia
index 105
new label wild rose
index 106
new label sweet william
index 107
new label rose
index 108
new label wild rose
index 109
new label foxglove
index 110
new label barberton daisy
index 111
new label camellia
index 112
new label cosmos
index 113
new label iris
index 114
new label wild geranium
index 115
new label tiger lily
index 116
new label anthurium
index 117
new label cape flower
index 118
new label yellow iris
index 119
new label pink primrose
index 120
new label common dandelion
index 121
new label hippeastrum
index 122
new label iris
index 123
new label artichoke
index 124
new label iris
index 125
new label wild geranium
index 126
new label common dandelion
index 127
new label sunflower
index 128
new label sweet william
index 129
new label morning glory
index 130
new label rose
index 131
new label osteospermum
index 132
new label orange dahlia
index 133
new label daisy
index 134
new label buttercup
index 135
new label common tulip
index 136
new label giant white arum lily
index 137
new label bougainvillea
index 138
new label magnolia
index 139
new label bougainvillea
index 140
new label water lily
index 141
new label yellow iris
index 142
new label rose
index 143
new label wild pansy
index 144
new label iris
index 145
new label wild rose
index 146
new label lotus
index 147
new label camellia
index 148
new label cyclamen
index 149
new label gaura
index 150
new label passion flower
index 151
new label common tulip
index 152
new label watercress
index 153
new label wild geranium
index 154
new label morning glory
index 155
new label camellia
index 156
new label iris
index 157
new label wild geranium
index 158
new label wild rose
index 159
new label rose
index 160
new label lenten rose
index 161
new label columbine
index 162
new label windflower
index 163
new label sweet william
index 164
new label lotus
index 165
new label wild rose
index 166
new label iris
index 167
new label sunflower
index 168
new label balloon flower
index 169
new label common dandelion
index 170
new label snapdragon
index 171
new label sunflower
index 172
new label purple coneflower
index 173
new label wild geranium
index 174
new label mexican petunia
index 175
new label wild rose
index 176
new label cyclamen
index 177
new label pink primrose
index 178
new label iris
index 179
new label buttercup
index 180
new label daisy
index 181
new label foxglove
index 182
new label wild geranium
index 183
new label snapdragon
index 184
new label magnolia
index 185
new label petunia
index 186
new label water lily
index 187
new label sweet william
index 188
new label rose
index 189
new label iris
index 190
new label sunflower
index 191
new label balloon flower
index 192
new label grape hyacinth
index 193
new label azalea
index 194
new label bee balm
index 195
new label marigold
index 196
new label marigold
index 197
new label wild pansy
index 198
new label wild geranium
index 199
new label iris
index 200
new label corn poppy
index 201
new label petunia
index 202
new label watercress
index 203
new label pink primrose
index 204
new label wild rose
index 205
new label rose
index 206
new label king protea
index 207
new label azalea
index 208
new label tree poppy
index 209
new label poinsettia
index 210
new label morning glory
index 211
new label hibiscus
index 212
new label pink primrose
index 213
new label iris
index 214
new label carnation
index 215
new label pink primrose
index 216
new label common dandelion
index 217
new label watercress
index 218
new label camellia
index 219
new label daisy
index 220
new label silverbush
index 221
new label sweet william
index 222
new label windflower
index 223
new label rose
index 224
new label sword lily
index 225
new label rose
index 226
new label foxglove
index 227
new label water lily
index 228
new label spear thistle
index 229
new label wild geranium
index 230
new label tree mallow
index 231
new label lilac hibiscus
index 232
new label common tulip
index 233
new label wild rose
index 234
new label wild pansy
index 235
new label wild geranium
index 236
new label common tulip
index 237
new label snapdragon
index 238
new label rose
index 239
new label morning glory
index 240
new label iris
index 241
new label daisy
index 242
new label spear thistle
index 243
new label common dandelion
index 244
new label common tulip
index 245
new label corn poppy
index 246
new label wild rose
index 247
new label common tulip
index 248
new label iris
index 249
new label yellow iris
index 250
new label iris
index 251
new label monkshood
index 252
new label wild geranium
index 253
new label anthurium
index 254
new label wild geranium
index 255
new label columbine
index 256
new label gazania
index 257
new label wild rose
index 258
new label spear thistle
index 259
new label daffodil
index 260
new label rose
index 261
new label pink primrose
index 262
new label frangipani
index 263
new label sweet william
index 264
new label toad lily
index 265
new label grape hyacinth
index 266
new label iris
index 267
new label magnolia
index 268
new label hippeastrum
index 269
new label windflower
index 270
new label yellow iris
index 271
new label iris
index 272
new label sweet william
index 273
new label frangipani
index 274
new label toad lily
index 275
new label azalea
index 276
new label prince of wales feathers
index 277
new label iris
index 278
new label camellia
index 279
new label daffodil
index 280
new label petunia
index 281
new label pink-yellow dahlia
index 282
new label snapdragon
index 283
new label gaura
index 284
new label spear thistle
index 285
new label daisy
index 286
new label common dandelion
index 287
new label bee balm
index 288
new label cyclamen
index 289
new label wild geranium
index 290
new label monkshood
index 291
new label magnolia
index 292
new label rose
index 293
new label morning glory
index 294
new label pink primrose
index 295
new label rose
index 296
new label pink primrose
index 297
new label cyclamen
index 298
new label iris
index 299
new label sunflower
index 300
new label orange dahlia
index 301
new label cyclamen
index 302
new label monkshood
index 303
new label morning glory
index 304
new label hibiscus
index 305
new label daisy
index 306
new label water lily
index 307
new label cyclamen
index 308
new label grape hyacinth
index 309
new label wild pansy
index 310
new label petunia
index 311
new label common dandelion
index 312
new label wild geranium
index 313
new label lotus
index 314
new label carnation
index 315
new label wild rose
index 316
new label wild rose
index 317
new label daisy
index 318
new label wild rose
index 319
new label wallflower
index 320
new label thorn apple
index 321
new label wild geranium
index 322
new label marigold
index 323
new label primula
index 324
new label sunflower
index 325
new label sunflower
index 326
new label hibiscus
index 327
new label anthurium
index 328
new label bird of paradise
index 329
new label gazania
index 330
new label thorn apple
index 331
new label tiger lily
index 332
new label wild geranium
index 333
new label sunflower
index 334
new label watercress
index 335
new label wild rose
index 336
new label wild geranium
index 337
new label iris
index 338
new label black-eyed susan
index 339
new label artichoke
index 340
new label sunflower
index 341
new label daisy
index 342
new label iris
index 343
new label common tulip
index 344
new label common tulip
index 345
new label cautleya spicata
index 346
new label water lily
index 347
new label windflower
index 348
new label columbine
index 349
new label water lily
index 350
new label globe thistle
index 351
new label orange dahlia
index 352
new label corn poppy
index 353
new label daisy
index 354
new label tree poppy
index 355
new label watercress
index 356
new label carnation
index 357
new label clematis
index 358
new label common dandelion
index 359
new label king protea
index 360
new label hippeastrum
index 361
new label foxglove
index 362
new label wild rose
index 363
new label spear thistle
index 364
new label gazania
index 365
new label iris
index 366
new label spear thistle
index 367
new label buttercup
index 368
new label wild rose
index 369
new label common tulip
index 370
new label wild geranium
index 371
new label poinsettia
index 372
new label sunflower
index 373
new label morning glory
index 374
new label rose
index 375
new label wallflower
index 376
new label pink primrose
index 377
new label primula
index 378
new label wild rose
index 379
new label lenten rose
index 380
new label sunflower
index 381
new label iris
index 382
new label iris
index 383
new label orange dahlia
index 384
new label daisy
index 385
new label sunflower
index 386
new label lotus
index 387
new label poinsettia
index 388
new label desert-rose
index 389
new label pincushion flower
index 390
new label sunflower
index 391
new label wallflower
index 392
new label azalea
index 393
new label iris
index 394
new label daisy
index 395
new label petunia
index 396
new label daisy
index 397
new label iris
index 398
new label tiger lily
index 399
new label iris
index 400
new label ruby-lipped cattleya
index 401
new label columbine
index 402
new label anthurium
index 403
new label black-eyed susan
index 404
new label sunflower
index 405
new label frangipani
index 406
new label wild geranium
index 407
new label pink primrose
index 408
new label yellow iris
index 409
new label bougainvillea
index 410
new label wild rose
index 411
new label daisy
index 412
new label water lily
index 413
new label mallow
index 414
new label iris
index 415
new label wild rose
index 416
new label carnation
index 417
new label morning glory
index 418
new label wild geranium
index 419
new label rose
index 420
new label primula
index 421
new label hibiscus
index 422
new label water lily
index 423
new label black-eyed susan
index 424
new label bougainvillea
index 425
new label spear thistle
index 426
new label wallflower
index 427
new label common dandelion
index 428
new label common dandelion
index 429
new label sunflower
index 430
new label sunflower
index 431
new label gazania
index 432
new label iris
index 433
new label pink primrose
index 434
new label wild rose
index 435
new label tiger lily
index 436
new label petunia
index 437
new label bougainvillea
index 438
new label buttercup
index 439
new label bee balm
index 440
new label tiger lily
index 441
new label rose
index 442
new label common tulip
index 443
new label grape hyacinth
index 444
new label pincushion flower
index 445
new label iris
index 446
new label foxglove
index 447
new label geranium
index 448
new label wild rose
index 449
new label common tulip
index 450
new label cyclamen
index 451
new label iris
index 452
new label windflower
index 453
new label gazania
index 454
new label bird of paradise
index 455
new label wild geranium
index 456
new label marigold
index 457
new label wild rose
index 458
new label daisy
index 459
new label great masterwort
index 460
new label bougainvillea
index 461
new label artichoke
index 462
new label common tulip
index 463
new label love in the mist
index 464
new label wild rose
index 465
new label sunflower
index 466
new label common tulip
index 467
new label common tulip
index 468
new label wild geranium
index 469
new label daisy
index 470
new label thorn apple
index 471
new label wild rose
index 472
new label wild rose
index 473
new label barberton daisy
index 474
new label trumpet creeper
index 475
new label bird of paradise
index 476
new label yellow iris
index 477
new label common dandelion
index 478
new label cape flower
index 479
new label iris
index 480
new label tree poppy
index 481
new label iris
index 482
new label wild rose
index 483
new label geranium
index 484
new label sword lily
index 485
new label bromelia
index 486
new label wild geranium
index 487
new label pink primrose
index 488
new label watercress
index 489
new label grape hyacinth
index 490
new label wild geranium
index 491
new label wild rose
index 492
new label foxglove
index 493
new label wild rose
index 494
new label watercress
index 495
new label bishop of llandaff
index 496
new label purple coneflower
index 497
new label cyclamen
index 498
new label iris
index 499
new label wild rose
index 500
new label sunflower
index 501
new label bougainvillea
index 502
new label spear thistle
index 503
new label sunflower
index 504
new label iris
index 505
new label common dandelion
index 506
new label stemless gentian
index 507
new label tiger lily
index 508
new label poinsettia
index 509
new label buttercup
index 510
new label bishop of llandaff
index 511
new label camellia
index 512
new label sunflower
index 513
new label columbine
index 514
new label wallflower
index 515
new label common dandelion
index 516
new label iris
index 517
new label thorn apple
index 518
new label gazania
index 519
new label buttercup
index 520
new label prince of wales feathers
index 521
new label sunflower
index 522
new label wild rose
index 523
new label pink-yellow dahlia
index 524
new label magnolia
index 525
new label wild geranium
index 526
new label cyclamen
index 527
new label common tulip
index 528
new label wild rose
index 529
new label yellow iris
index 530
new label camellia
index 531
new label wild geranium
index 532
new label wild geranium
index 533
new label hibiscus
index 534
new label rose
index 535
new label sweet william
index 536
new label water lily
index 537
new label poinsettia
index 538
new label spear thistle
index 539
new label bird of paradise
index 540
new label wallflower
index 541
new label windflower
index 542
new label cyclamen
index 543
new label windflower
index 544
new label clematis
index 545
new label sunflower
index 546
new label daisy
index 547
new label wild geranium
index 548
new label iris
index 549
new label azalea
index 550
new label balloon flower
index 551
new label buttercup
index 552
new label sunflower
index 553
new label common dandelion
index 554
new label frangipani
index 555
new label sweet william
index 556
new label sunflower
index 557
new label wild rose
index 558
new label rose
index 559
new label carnation
index 560
new label tree poppy
index 561
new label foxglove
index 562
new label spear thistle
index 563
new label common tulip
index 564
new label columbine
index 565
new label yellow iris
index 566
new label wild geranium
index 567
new label iris
index 568
new label common dandelion
index 569
new label toad lily
index 570
new label common dandelion
index 571
new label wild geranium
index 572
new label sunflower
index 573
new label columbine
index 574
new label marigold
index 575
new label anthurium
index 576
new label sword lily
index 577
new label sunflower
index 578
new label wild geranium
index 579
new label windflower
index 580
new label morning glory
index 581
new label azalea
index 582
new label magnolia
index 583
new label iris
index 584
new label bishop of llandaff
index 585
new label desert-rose
index 586
new label magnolia
index 587
new label rose
index 588
new label sunflower
index 589
new label bee balm
index 590
new label yellow iris
index 591
new label primula
index 592
new label hibiscus
index 593
new label sunflower
index 594
new label rose
index 595
new label wild rose
index 596
new label primula
index 597
new label daisy
index 598
new label daisy
index 599
new label monkshood
index 600
new label clematis
index 601
new label buttercup
index 602
new label buttercup
index 603
new label spear thistle
index 604
new label bishop of llandaff
index 605
new label wild geranium
index 606
new label silverbush
index 607
new label wild rose
index 608
new label spear thistle
index 609
new label yellow iris
index 610
new label iris
index 611
new label cyclamen
index 612
new label common tulip
index 613
new label buttercup
index 614
new label foxglove
index 615
new label cape flower
index 616
new label wild geranium
index 617
new label rose
index 618
new label bougainvillea
index 619
new label iris
index 620
new label wild rose
index 621
new label wild geranium
index 622
new label iris
index 623
new label morning glory
index 624
new label wild geranium
index 625
new label morning glory
index 626
new label artichoke
index 627
new label grape hyacinth
index 628
new label artichoke
index 629
new label tiger lily
index 630
new label yellow iris
index 631
new label barberton daisy
index 632
new label thorn apple
index 633
new label bird of paradise
index 634
new label sunflower
index 635
new label wild rose
index 636
new label spear thistle
index 637
new label frangipani
index 638
new label pink primrose
index 639
new label common dandelion
index 640
new label thorn apple
index 641
new label stemless gentian
index 642
new label wild geranium
index 643
new label artichoke
index 644
new label sword lily
index 645
new label daisy
index 646
new label poinsettia
index 647
new label primula
index 648
new label buttercup
index 649
new label thorn apple
index 650
new label iris
index 651
new label snapdragon

In [108]:
submission_csv.head(10)

          id               label
0  b48c962e0          corn poppy
1  a13d3dfa4             petunia
2  94269c190                rose
3  bcb18c6e4       wild geranium
4  d15a4d94c    common dandelion
5  914b0e71b       sweet william
6  065c9b5be  pink-yellow dahlia
7  dd8b1aaca          watercress
8  8c39d1b41              cosmos
9  e2fdce920       wild geranium

Preprocess testing data...

In [ ]:
preprocessed_test_df = preprocess(test_df)
preprocessed_test_df.head(5)

Check to see if any issues are in the testing data (e.g. n/a)

In [ ]:
preprocessed_test_df.isnull().any()

In [ ]:
raw_preds, _, decoded = learn.get_preds(dl=dls_test, with_decoded=True)

In [ ]:
raw_preds[:5], decoded[:5]

In [ ]:
dls_test.show_batch()

In [ ]:
df_submission = pd.DataFrame({'PassengerId': preprocessed_test_df.PassengerId
                              , 'Survived': decoded.flatten()})

In [ ]:
df_submission.head(5)

In [ ]:
df_submission.to_csv(os.path.join(path, 'submission.csv'), index=False)

# Test data prediction

In [ ]:
# tpreds=[]
# for i in range(len(preprocessed_test_df)):
#     _, _, probs = learn.predict(preprocessed_test_df.iloc[i])
#     tpreds+=[probs.numpy()[0]]